GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5hbWUiOiJCdWRpIiwiaWF0IjoxNjc0NDg4MjQyLCJleHAiOjE2NzQ0ODgyNTd9.rdeMwas1eTX9dP2-WwUMqKwPEyAP-PtE8wguK9CNDmI

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Budi",
    "password": "restan"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "name": "Budi",
    "password": "restan"
}
###
GET http://localhost:5000/token
###
DELETE http://localhost:5000/logout