GET http://localhost:3100/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJCdWRpIiwiaWF0IjoxNjc0ODk0MDM3LCJleHAiOjE2NzQ4OTQwNTJ9.BP59t7hAgIyLAtpOfmPHiogPFifPdJPcjVRkxfZ4EU8
###
POST http://localhost:3100/api/users/users
Content-Type: application/json

{
    "name": "Budi",
    "password": "restan"
}
###
POST http://localhost:3100/api/users/login
Content-Type: application/json

{
    "name": "Budi",
    "password": "restan"
}
###
GET http://localhost:3100/api/users/token
###
DELETE http://localhost:3100/api/users/logout